"""Message formatters for morning todo and daily summary."""

import os
from datetime import date


def _dr_ma_mention() -> str:
    """Return a Slack @mention for Dr Ma, or fallback to plain text."""
    user_id = os.environ.get("DR_MA_USER_ID")
    return f"<@{user_id}>" if user_id else "@Dr Ma"


def build_morning_message(todos: list[str]) -> tuple[str, list[dict]]:
    """Build a Slack Block Kit morning todo message.

    Args:
        todos: List of todo item strings.

    Returns:
        Tuple of (plain_text_fallback, blocks).
    """
    today = date.today().strftime("%A, %B %-d, %Y")
    mention = _dr_ma_mention()
    todo_lines = "\n".join(f"• {item}" for item in todos) if todos else "• Nothing scheduled today"

    # Plain-text fallback for notifications
    plain_text = f"{mention} 🌅 Good morning! Here's today's todo list ({today}):\n{todo_lines}"

    blocks = [
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"{mention} 🌅 *Good morning! Here's today's todo list:*"},
        },
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"Morning Todo List – {today}",
                "emoji": True,
            },
        },
        {"type": "divider"},
    ]

    if todos:
        for item in todos:
            blocks.append(
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": f"☐  {item}"},
                }
            )
    else:
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": "_Nothing scheduled today._"},
            }
        )

    blocks.append({"type": "divider"})
    blocks.append(
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": "Have a great day! 😊"}
            ],
        }
    )

    return plain_text, blocks


def build_summary_message(summary_text: str, stats: dict) -> tuple[str, list[dict]]:
    """Build a Slack Block Kit end-of-day summary message.

    Args:
        summary_text: AI-generated narrative summary string.
        stats: Dict of key metrics, e.g. {"patients_seen": 12, "production": "$4,200"}.

    Returns:
        Tuple of (plain_text_fallback, blocks).
    """
    today = date.today().strftime("%A, %B %-d, %Y")
    mention = _dr_ma_mention()
    plain_text = f"{mention} 📋 Daily Summary – {today}\n\n{summary_text}"

    blocks = [
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"{mention} 📋 *Daily Summary:*"},
        },
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"Daily Summary – {today}",
                "emoji": True,
            },
        },
        {"type": "divider"},
    ]

    # Stats section (if any)
    if stats:
        stat_lines = "\n".join(f"*{k}:* {v}" for k, v in stats.items())
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": stat_lines},
            }
        )
        blocks.append({"type": "divider"})

    # AI summary
    blocks.append(
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Summary:*\n{summary_text}"},
        }
    )
    blocks.append({"type": "divider"})
    blocks.append(
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": "Generated by maoffice 🤖"}
            ],
        }
    )

    return plain_text, blocks
