"""Message formatters for morning todo and daily summary."""

import os
from datetime import date


def _dr_ma_mention() -> str:
    """Return a Slack @mention for Dr Ma, or fallback to plain text."""
    user_id = os.environ.get("DR_MA_USER_ID")
    return f"<@{user_id}>" if user_id else "@Dr Ma"


def build_morning_message(todos: list[str]) -> tuple[str, list[dict]]:
    """Build a Slack Block Kit morning todo message.

    Args:
        todos: List of todo item strings.

    Returns:
        Tuple of (plain_text_fallback, blocks).
    """
    today = date.today().strftime("%A, %B %-d, %Y")
    mention = _dr_ma_mention()
    todo_lines = "\n".join(f"• {item}" for item in todos) if todos else "• Nothing scheduled today"

    # Plain-text fallback for notifications
    plain_text = f"{mention} 🌅 Good morning! Here's today's todo list ({today}):\n{todo_lines}"

    blocks = [
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"{mention} 🌅 *Good morning! Here's today's todo list:*"},
        },
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"Morning Todo List – {today}",
                "emoji": True,
            },
        },
        {"type": "divider"},
    ]

    if todos:
        for item in todos:
            blocks.append(
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": f"☐  {item}"},
                }
            )
    else:
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": "_Nothing scheduled today._"},
            }
        )

    blocks.append({"type": "divider"})
    blocks.append(
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": "Have a great day! 😊"}
            ],
        }
    )

    return plain_text, blocks


def build_summary_message(summary_text: str, stats: dict) -> tuple[str, list[dict]]:
    """Build a Slack Block Kit end-of-day summary message.

    Args:
        summary_text: AI-generated narrative summary string.
        stats: Dict of key metrics, e.g. {"patients_seen": 12, "production": "$4,200"}.

    Returns:
        Tuple of (plain_text_fallback, blocks).
    """
    today = date.today().strftime("%A, %B %-d, %Y")
    mention = _dr_ma_mention()
    plain_text = f"{mention} 📋 Daily Summary – {today}\n\n{summary_text}"

    blocks = [
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"{mention} 📋 *Daily Summary:*"},
        },
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"Daily Summary – {today}",
                "emoji": True,
            },
        },
        {"type": "divider"},
    ]

    # Stats section (if any)
    if stats:
        stat_lines = "\n".join(f"*{k}:* {v}" for k, v in stats.items())
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": stat_lines},
            }
        )
        blocks.append({"type": "divider"})

    # AI summary
    blocks.append(
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Summary:*\n{summary_text}"},
        }
    )
    blocks.append({"type": "divider"})
    blocks.append(
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": "Generated by maoffice 🤖"}
            ],
        }
    )

    return plain_text, blocks


def _fmt_currency(amount) -> str:
    """Format a float as currency string, e.g. 4200.0 → '$4,200'."""
    return f"${float(amount):,.0f}"


def build_morning_message_v2(
    schedule: list[dict],
    cancellations: list[dict],
    open_slots: list[dict],
) -> tuple[str, list[dict]]:
    """Build the Phase 2 morning message with live OpenDental data.

    Args:
        schedule: List of today's appointments from opendental.get_today_schedule().
        cancellations: Today's broken/unscheduled from opendental.get_today_cancellations().
        open_slots: Next-7-days open slots from opendental.get_open_slots().

    Returns:
        Tuple of (plain_text_fallback, blocks).
    """
    today = date.today().strftime("%A, %B %-d, %Y")
    mention = _dr_ma_mention()

    # Build plain text
    apt_lines = "\n".join(
        f"• {a['AptDateTime'][11:16]}  {a['PatientName']}  [{a.get('ProvAbbr', '')}]  {a.get('ProcDescript', '')}"
        for a in schedule
    ) or "• No appointments scheduled today."

    slot_lines = "\n".join(
        f"• {s['SchedDate']}  {s.get('ProvAbbr', '')}  — {s['OpenSlots']} open slot(s)"
        for s in open_slots
    ) or "• Schedule is full this week."

    cancel_lines = "\n".join(
        f"• {c['PatientName']}  {c.get('ProcDescript', '')}"
        for c in cancellations
    ) or "• None"

    plain_text = (
        f"{mention} 🌅 Good morning! Here's your schedule for {today}:\n"
        f"{apt_lines}\n\n"
        f"Cancellations today:\n{cancel_lines}\n\n"
        f"Open slots next 7 days:\n{slot_lines}"
    )

    # Build blocks
    blocks = [
        {"type": "section", "text": {"type": "mrkdwn", "text": f"{mention} 🌅 *Good morning!*"}},
        {"type": "header", "text": {"type": "plain_text", "text": f"Schedule — {today}", "emoji": True}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": f"*Today's Appointments ({len(schedule)})*\n{apt_lines}"}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": f"*Cancellations / No-shows*\n{cancel_lines}"}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": f"*Open Slots — Next 7 Days*\n{slot_lines}"}},
        {"type": "divider"},
        {"type": "context", "elements": [{"type": "mrkdwn", "text": "Have a great day! 😊"}]},
    ]

    return plain_text, blocks


def build_summary_message_v2(
    ai_summary: str,
    production: dict,
    collections: dict,
    aging: dict,
    claims: dict,
    cancellations: list[dict],
) -> tuple[str, list[dict]]:
    """Build the Phase 2 evening summary with live OpenDental data.

    Returns:
        Tuple of (plain_text_fallback, blocks).
    """
    today = date.today().strftime("%A, %B %-d, %Y")
    mention = _dr_ma_mention()

    prod = _fmt_currency(production.get("production", 0))
    proc_count = production.get("procedure_count", 0)
    pat_pay = _fmt_currency(collections.get("patient_payments", 0))
    ins_pay = _fmt_currency(collections.get("insurance_payments", 0))
    total_collect = _fmt_currency(
        float(collections.get("patient_payments", 0)) + float(collections.get("insurance_payments", 0))
    )

    aging_text = (
        f"*AR Aging:* "
        f"0-30: {_fmt_currency(aging.get('bal_0_30', 0))} | "
        f"31-60: {_fmt_currency(aging.get('bal_31_60', 0))} | "
        f"61-90: {_fmt_currency(aging.get('bal_61_90', 0))} | "
        f"91-120: {_fmt_currency(aging.get('bal_91_120', 0))} | "
        f"120+: {_fmt_currency(aging.get('bal_over_120', 0))}"
    )

    cancel_lines = "\n".join(
        f"• {c['PatientName']}  {c.get('ProcDescript', '')}" for c in cancellations
    ) or "• None"

    plain_text = (
        f"{mention} 📋 Daily Summary — {today}\n"
        f"Production: {prod} ({proc_count} procedures)\n"
        f"Collections: {total_collect} (patient: {pat_pay} | insurance: {ins_pay})\n"
        f"Pending claims: {claims.get('pending_count', 0)} ({_fmt_currency(claims.get('pending_total', 0))})\n\n"
        f"{ai_summary}"
    )

    blocks = [
        {"type": "section", "text": {"type": "mrkdwn", "text": f"{mention} 📋 *Daily Summary*"}},
        {"type": "header", "text": {"type": "plain_text", "text": f"Daily Summary — {today}", "emoji": True}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": (
            f"*Production:* {prod}  ({proc_count} procedures)\n"
            f"*Collections:* {total_collect}  (patient: {pat_pay} | insurance: {ins_pay})"
        )}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": aging_text}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": (
            f"*Claims:* {claims.get('pending_count', 0)} pending ({_fmt_currency(claims.get('pending_total', 0))}) | "
            f"{claims.get('rejected_count', 0)} rejected ({_fmt_currency(claims.get('rejected_total', 0))})"
        )}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": f"*Cancellations / No-shows:*\n{cancel_lines}"}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": f"*AI Summary:*\n{ai_summary}"}},
        {"type": "divider"},
        {"type": "context", "elements": [{"type": "mrkdwn", "text": "Generated by maoffice 🤖"}]},
    ]

    return plain_text, blocks
